### PR TITLE
get locale data

### PR DESCRIPTION
**Pull request by skynet67**

### CODE REVIEW

**Comment by ssteveli** [comment]
Did we have a requirement to make these overridable by the OEM?

**Comment by skynet67** [comment]
a line from the task >>We will need to pass on locale from the phone as part of the risk data for issuers

I don't know why they asked us to add such functionality into SDK.

**Comment by ssteveli** [comment]
@andybfp : Do you envision this data being overridable from the OEM?  

@skynet67 This PR doesn't address it getting sent with the risk data, is that coming in another PR?

**Comment by andybfp** [comment]
@andybfp <https://github.com/andybfp> : Do you envision this data being
overridable from the OEM?

My original intention (I'm a step away these days) was for the phone local
to be passed by default for the language parameter in the webapp config and
thus also be overridable by the OEM if they wanted something different.
That said, I think that stategy has some weaknesses and thus I requested
some review from others. Perhaps this should be sent as riskdata and not
re-use/re-purpose the existing language parameter. Or perhaps this should
be sent as risk data that the OEM can't override without taking fairly
drastic measures (making their own SDK).

I haven't reviewed the story which was created after my initial suggestion
nor Vlad's code change, but my opinion today would be that we keep the
language parameter tied to the presentation language of the WebApp and no
re-use it for other purposes (such as risk data) and then send this local
value by default with no OEM override for us to use as risk data as we see
fit. If the OEM wants to override the location data used for risk (such as
providing the location of the device via some other method like lat/long
GPS) that would be a separate parameter?

But to be fair to Vlad here, my ideas today don't match up with my ideas
from a few weeks ago and my answers are likely to raise more questions then
they answer. If from a code review perspective we need to circle up on the
story/requirements let's ask Vlad to pause and do that. Sorry Scott
@ssteveli but given your review can you make that call? We need to review
the story requirements in order to get Vlad the right feedback?

**Comment by andybfp** [comment]
and I keep typing "local" when I intend "locale"

**Comment by andybfp** [comment]
@skynet67 We've clarified on our end and the original story is accurate but I want to answer your questions. First, please send `locale` of the phone as a new risk-data field (amongst the other risk data being sent in response to the RTM Risk Data Request). That's the original/existing story. Let me know if there are any questions on this aspect.  

In response to Scott, there is no need for the OEM to override this new risk data field called `locale` and it's our believe (which you can/should correct us on if incorrect) that `locale` is a standard setting of the phone which you can query.  

You mentioned you don't know why we'd add this to the SDK. The purpose is that we need to know both language and country setting of the phone (`locale` provides both to my understanding) and thus we either need to ask the OEM to send it somehow OR we can alleviate them of needing to do any work or even think about it by having our SDKs do it for them out of the box. Make sense?  

If this leaves you wondering why we're not doing it another way please let us know, perhaps we're missing something obvious about how to get the country and language setting of the phone. Above our our assumptions.

Reopen PR when this is ready for our review.

**Pull request closed without merging**
