### PR TITLE
IdVerification remove some variables

### PR DESCRIPTION
**Pull request by skynet67**

### CODE REVIEW

**Comment by jeremiahthomasharris** [comment]
@skynet67 I think the one piece missing here is 
"daysSinceLastAccountActivity & deviceLostMode should both be sent as integers, days since the date."
Rest of it looks great.

**Comment by skynet67** [comment]
@jeremiahthomasharris probably we should do the same for iOS as well
https://github.com/fitpay/fitpay-ios-sdk/blob/303154dacceaeb0da1b267eeb1ca04cf9efc6eb9/FitpaySDK/Rtm/Models/IdVerification.swift#L18

**Comment by jeremiahthomasharris** [comment]
Vlad, Think we are are getting lost in translation here. The ticket should have been more clear. 
The variable should indeed be a `Date`. It should then be converted into an `Integer` when it is sent to the backend.

**Comment by climbonbelay** [comment]
Needs some tests

**Comment by jeremiahthomasharris** [comment]
Can we do this without using joda-time? it looks like Java 8 has pretty good support.

**Pull request merged**
