### PR TITLE
ApduCommand with continueOnFailure field

### PR DESCRIPTION
**Pull request by skynet67**

### CODE REVIEW

**Comment by ssteveli** [comment]
@bpwalford : were there serialization here in the SDK failures when this flag was added to the JSON from the API?

**Comment by bpwalford** [comment]
@ssteveli Are you asking if there will be serialization issues in the Android app since these fields don't exist on old commits? If so, won't the fields default to false?

**Comment by ssteveli** [comment]
I had understood from @andybfp that this flag being added to the platform was causing issues in the mobile applications... which **implied** to me that it must have broken serialization, meaning that the SDK was not following our _ignore what you don't understand_ rule. 

So before approving this PR, I'm trying to answer that very question... is the SDK ignoring what it doesn't understand?  If not, I want that fixed.

**Comment by skynet67** [comment]
that filed will not breake serialization on Android.

**Comment by andybfp** [comment]
I mistakenly created a misunderstanding here - Scott's concerns are resolved and this PR is ready to merge unless someone else has an issue.

**Pull request merged**
